# from https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "ini"
file-types = [
  "conf",

  "ini",
  "service",
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  "container",
  "volume",
  "kube",
  "network",
]
